server:
  port: 8081

spring:
  jpa:
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3307/coupon?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root


  logging:
    file:
      path: ./logs
    config: classpath:logback-spring.xml
